language: go
go:
- '1.11'
script: go test -v -covermode=count -coverprofile=coverage.out -bench=.
after_success:
- go get github.com/mattn/goveralls
- $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVER_TOKEN

env:
  global:
    secure: pooPhNBUm2wBALaJfg6GYGwwswDvkizwi5JRz6qoCFfkaNECgyndt/Ip7J0B23ooUZQLzpZsQl2Jp7dqaeDSFlS4yj16tkYJ5z3TsUuggSJ4M8OkRGXeaeW4v/1e1Q8ow+Mi2thYNfHYwEKCMED4zOpnD5MJ0Xfziq3iiJtG0LvfY8roo05ciO8kZ3CuiS1WbdEKfRSIhCR7eG3d7cGt3ndgk/Bsht3TZzM7NVK6M6wNDjh90lWWqkdLfNuWnla8OnmwNqmZd5/ji2B7hLhVv95HCM6+8AH+rP9cebPMLNSajkrTQrx52TXWzACL6utvlvu5tfOWpd37I7zYEeMNIfberWDvOe6ZB2j6ISuohXo8iLxcocyJZLJSsm43BmXO49py9fQenpjt+2TkHwRMEIGW+YGtsXPM9tGlInUVjoMQinjYXouMJ1cwDYEaEF+/l2UdNjfXFEAyCvJQHg7fk96w7ZBVkWoMiaIol4zRVQqroyJj0AP/lJUhwnt5iDxuFAKlZFdoQLuYyth3JKq/NPDDcjrbqJU33X9wilq8JqUjCJL7tNzIq3xoivWKI3orzykp9RZ5voaC9by/VK//K3apP+caPZzKOgI8D4ph9FuqRfjxZ0ooAjJuqMS7YDrSWjXNTa/suoAWzqlyh3+9I/kYQYB8SDTqqx2DNTGvKwI=
